async function Module(moduleArg={}){var moduleRtn;var h=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,k=ba&&self.name?.startsWith("em-pthread"),da=[],ea="./this.program",fa=import.meta.url,ha="",ia,ja;if(aa||ba){try{ha=(new URL(".",fa)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var ka=console.log.bind(console),l=console.error.bind(console),la,ma,qa=!1,ra;function m(){p.buffer!=r.buffer&&sa()}var ta,ua,va;
if(k){var wa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.Aa;if("load"===d){let e=[];self.onmessage=f=>e.push(f);va=()=>{postMessage({Aa:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.pb)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({Aa:"callHandler",ob:f,mb:g})},"print"==f&&(ka=h[f]),"printErr"==f&&(l=h[f]);p=c.Bb;sa();ma=c.Cb;xa();ya()}else if("run"===d){za(c.xa);Aa(c.xa,0,0,1,0,0);Ba();Ca(c.xa);wa||=!0;try{Da(c.xb,c.Ra)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?wa&&Ea():d&&(l(`worker: received unknown command ${d}`),l(c)))}catch(e){throw Fa(),e;}}self.onmessage=a}var p,r,u,Ga,v,w,Ha,x,y,Ia=!1;function sa(){var a=p.buffer;r=new Int8Array(a);Ga=new Int16Array(a);u=new Uint8Array(a);new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);new Float32Array(a);Ha=new Float64Array(a);x=new BigInt64Array(a);y=new BigUint64Array(a)}
function Ja(){Ia=!0;if(k)va();else{if(!h.noFSInit&&!Ka){var a,b,c;Ka=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?A("stdin",a):La("/dev/tty","/dev/stdin");b?A("stdout",null,b):La("/dev/tty","/dev/stdout");c?A("stderr",null,c):La("/dev/tty1","/dev/stderr");Ma("/dev/stdin",0);Ma("/dev/stdout",1);Ma("/dev/stderr",1)}B.root=Na(B,null);C.S();Oa=!1}}
function Pa(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);qa=!0;a+=". Build with -sASSERTIONS for more info.";Ia&&Qa();a=new WebAssembly.RuntimeError(a);ua?.(a);throw a;}var Ra;async function Sa(a){if(!la)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Ra&&la)a=new Uint8Array(la);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ta(a,b){try{var c=await Sa(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),Pa(d)}}async function Ua(a){var b=Ra;if(!la)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return Ta(b,a)}
function Va(){Wa={z:Xa,B:Ya,j:Za,h:$a,M:ab,r:bb,J:cb,K:db,I:eb,g:fb,D:gb,o:hb,L:ib,p:jb,k:kb,G:lb,u:mb,C:nb,A:ob,v:pb,e:qb,F:Ca,O:rb,y:sb,s:tb,i:ub,f:vb,R:wb,N:xb,w:yb,b:zb,x:Ab,t:Bb,P:Cb,Q:Db,c:Eb,d:Fb,H:Gb,q:Hb,E:Ib,m:Jb,a:p,l:Kb,n:Lb};return{a:Wa}}
async function xa(){function a(d,e){C=d.exports;C=Mb();Nb.push(C.U);Ob=C.W;ma=e;d=C;h._main=Pb=d.T;Qb=d.V;Aa=d.X;Fa=d.Y;Rb=d.Z;Sb=d._;Tb=d.$;Ub=d.aa;Vb=d.ba;Qa=d.ca;Wb=d.da;Xb=d.ea;Yb=d.fa;Zb=d.ga;return C}var b=Va();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(k){var c=new WebAssembly.Instance(ma,Va());return a(c,ma)}Ra??=h.locateFile?h.locateFile?h.locateFile("vampire.wasm",ha):ha+"vampire.wasm":(new URL("vampire.wasm",import.meta.url)).href;
return function(d){return a(d.instance,d.module)}(await Ua(b))}class $b{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ac=a=>{a.terminate();a.onmessage=()=>{}},bc=a=>{for(;0<a.length;)a.shift()(h)},cc=[],E=0,dc=null,hc=a=>{0==F.length&&(ec(),fc(F[0]));var b=F.pop();if(!b)return 6;gc.push(b);G[a.xa]=b;b.xa=a.xa;b.postMessage({Aa:"run",xb:a.wb,Ra:a.Ra,xa:a.xa},a.lb);return 0},H=0,I=(a,b,...c)=>{for(var d=2*c.length,e=Zb(),f=Yb(8*d),g=f/8,n=0;n<c.length;n++){var t=c[n];"bigint"==typeof t?((m(),x)[g+2*n]=1n,(m(),x)[g+2*n+1]=t):((m(),x)[g+2*n]=0n,(m(),Ha)[g+2*n+1]=t)}a=Rb(a,0,d,f,b);Xb(e);return a};
function Kb(a){if(k)return I(0,1,a);ra=a;if(!(J||0<H)){for(var b of gc)ac(b);for(b of F)ac(b);F=[];gc=[];G={};h.onExit?.(a);qa=!0}throw new $b(a);}function ic(a){if(k)return I(1,0,a);Eb(a)}var Eb=a=>{ra=a;if(k)throw ic(a),"unwind";Kb(a)},F=[],gc=[],Nb=[],G={};function jc(){for(var a=2;a--;)ec();cc.push(async()=>{var b=kc();E++;h.monitorRunDependencies?.(E);await b;E--;h.monitorRunDependencies?.(E);0==E&&dc&&(b=dc,dc=null,b())})}
var lc=a=>{var b=a.xa;delete G[b];F.push(a);gc.splice(gc.indexOf(a),1);a.xa=0;Sb(b)};function Ba(){Nb.forEach(a=>a())}
var fc=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.Aa;if(g.Pa&&g.Pa!=Qb()){var n=G[g.Pa];n?n.postMessage(g,g.lb):l(`Internal error! Worker sent a message "${f}" to target pthread ${g.Pa}, but that thread no longer exists!`)}else if("checkMailbox"===f)Ea();else if("spawnThread"===f)hc(g);else if("cleanupThread"===f)mc(()=>{lc(G[g.yb])});else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)h[g.ob](...g.mb);else f&&l(`worker sent an unknown command ${f}`)};
a.onerror=f=>{l(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({Aa:"load",pb:c,Bb:p,Cb:ma})});async function kc(){if(!k)return Promise.all(F.map(fc))}
function ec(){if(h.mainScriptUrlOrBlob){var a=h.mainScriptUrlOrBlob;"string"!=typeof a&&(a=URL.createObjectURL(a));a=new Worker(a,{type:"module",name:"em-pthread"})}else a=new Worker(new URL("vampire.js",import.meta.url),{type:"module",name:"em-pthread"});F.push(a)}var nc=[];function za(a){var b=Number((m(),y)[(a+88)/8]);a=Number((m(),y)[(a+96)/8]);Wb(b,b-a);Xb(b)}
var Ob,Da=(a,b)=>{J=H=0;(function(c){J||0<H?ra=c:Tb(c)})((c=>Ob.get(BigInt(a)).call(null,BigInt(c)))(b))},J=!0,M=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a);function Xa(a,b){a=M(a);return Ob.get(BigInt(a))(b)}function oc(a,b,c,d){return k?I(2,1,a,b,c,d):Ya(a,b,c,d)}
function Ya(a,b,c,d){a=M(a);b=M(b);c=M(c);d=M(d);if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(k&&0===e.length)return oc(a,b,c,d);a={wb:c,xa:a,Ra:d,lb:e};return k?(a.Aa="spawnThread",postMessage(a,e),0):hc(a)}
var pc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},qc=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=pc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},rc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},sc=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],
tc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),uc=a=>{(uc=tc())(a)},vc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=pc(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},wc=new TextDecoder,xc=(a,b)=>{for(var c=b+void 0;a[b]&&!(b>=c);)++b;return b},yc=a=>{var b=xc(a,0);return wc.decode(a.buffer?a.slice(0,
b):new Uint8Array(a.slice(0,b)))},zc=[],Ac=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Bc=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=
128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Cc=[];function Dc(a,b){Cc[a]={input:[],output:[],Ba:b};Ec(a,Fc)}
var Fc={open(a){var b=Cc[a.node.Fa];if(!b)throw new N(43);a.ka=b;a.seekable=!1},close(a){a.ka.Ba.Ha(a.ka)},Ha(a){a.ka.Ba.Ha(a.ka)},read(a,b,c,d){if(!a.ka||!a.ka.Ba.bb)throw new N(60);for(var e=0,f=0;f<d;f++){try{var g=a.ka.Ba.bb(a.ka)}catch(n){throw new N(29);}if(void 0===g&&0===e)throw new N(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.za=Date.now());return e},write(a,b,c,d){if(!a.ka||!a.ka.Ba.Va)throw new N(60);try{for(var e=0;e<d;e++)a.ka.Ba.Va(a.ka,b[c+e])}catch(f){throw new N(29);
}d&&(a.node.pa=a.node.oa=Date.now());return e}},Gc={bb(){a:{if(!zc.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Ac(a)+1);a=Bc(a,b,0,b.length);b.length=a;zc=b}b=zc.shift()}return b},Va(a,b){null===b||10===b?(ka(yc(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ha(a){0<a.output?.length&&(ka(yc(a.output)),a.output=[])},rb(){return{Gb:25856,Ib:5,Fb:191,Hb:35387,Eb:[3,28,127,21,4,0,1,
0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},sb(){return 0},tb(){return[24,80]}},Hc={Va(a,b){null===b||10===b?(l(yc(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ha(a){0<a.output?.length&&(l(yc(a.output)),a.output=[])}},O={wa:null,va(){return O.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.wa||(O.wa={dir:{node:{qa:O.ia.qa,ya:O.ia.ya,Ia:O.ia.Ia,Ma:O.ia.Ma,kb:O.ia.kb,Qa:O.ia.Qa,Na:O.ia.Na,Wa:O.ia.Wa,Oa:O.ia.Oa},stream:{ua:O.ha.ua}},
file:{node:{qa:O.ia.qa,ya:O.ia.ya},stream:{ua:O.ha.ua,read:O.ha.read,write:O.ha.write,gb:O.ha.gb,ib:O.ha.ib}},link:{node:{qa:O.ia.qa,ya:O.ia.ya,Ka:O.ia.Ka},stream:{}},$a:{node:{qa:O.ia.qa,ya:O.ia.ya},stream:Ic}});c=Jc(a,b,c,d);P(c.mode)?(c.ia=O.wa.dir.node,c.ha=O.wa.dir.stream,c.ja={}):32768===(c.mode&61440)?(c.ia=O.wa.file.node,c.ha=O.wa.file.stream,c.ma=0,c.ja=null):40960===(c.mode&61440)?(c.ia=O.wa.link.node,c.ha=O.wa.link.stream):8192===(c.mode&61440)&&(c.ia=O.wa.$a.node,c.ha=O.wa.$a.stream);
c.za=c.pa=c.oa=Date.now();a&&(a.ja[b]=c,a.za=a.pa=a.oa=c.za);return c},Kb(a){return a.ja?a.ja.subarray?a.ja.subarray(0,a.ma):new Uint8Array(a.ja):new Uint8Array(0)},ia:{qa(a){var b={};b.ab=8192===(a.mode&61440)?a.id:1;b.eb=a.id;b.mode=a.mode;b.jb=1;b.uid=0;b.cb=0;b.Fa=a.Fa;P(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ma:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.za=new Date(a.za);b.pa=new Date(a.pa);b.oa=new Date(a.oa);b.Ya=4096;b.Za=Math.ceil(b.size/b.Ya);return b},ya(a,b){for(var c of["mode",
"atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ma!=b&&(0==b?(a.ja=null,a.ma=0):(c=a.ja,a.ja=new Uint8Array(b),c&&a.ja.set(c.subarray(0,Math.min(b,a.ma))),a.ma=b)))},Ia(){O.Sa||(O.Sa=new N(44),O.Sa.stack="<generic error, no stack>");throw O.Sa;},Ma(a,b,c,d){return O.createNode(a,b,c,d)},kb(a,b,c){try{var d=Q(b,c)}catch(f){}if(d){if(P(a.mode))for(var e in d.ja)throw new N(55);Kc(d)}delete a.parent.ja[a.name];b.ja[c]=a;a.name=c;b.oa=b.pa=a.parent.oa=a.parent.pa=Date.now()},
Qa(a,b){delete a.ja[b];a.oa=a.pa=Date.now()},Na(a,b){var c=Q(a,b),d;for(d in c.ja)throw new N(55);delete a.ja[b];a.oa=a.pa=Date.now()},Wa(a){return[".","..",...Object.keys(a.ja)]},Oa(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},Ka(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},ha:{read(a,b,c,d,e){var f=a.node.ja;if(e>=a.node.ma)return 0;a=Math.min(a.node.ma-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===
(m(),r).buffer&&(f=!1);if(!d)return 0;a=a.node;a.pa=a.oa=Date.now();if(b.subarray&&(!a.ja||a.ja.subarray)){if(f)return a.ja=b.subarray(c,c+d),a.ma=d;if(0===a.ma&&0===e)return a.ja=b.slice(c,c+d),a.ma=d;if(e+d<=a.ma)return a.ja.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.ja?a.ja.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.ja,a.ja=new Uint8Array(f),0<a.ma&&a.ja.set(g.subarray(0,a.ma),0));if(a.ja.subarray&&b.subarray)a.ja.set(b.subarray(c,c+d),e);else for(f=0;f<
d;f++)a.ja[e+f]=b[c+f];a.ma=Math.max(a.ma,e+d);return d},ua(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ma);if(0>b)throw new N(28);return b},gb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.ja;if(e&2||!a||a.buffer!==(m(),r).buffer){d=!0;Pa();e=void 0;if(!e)throw new N(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);(m(),r).set(a,e)}}else d=!1,e=a.byteOffset;return{Nb:e,Db:d}},ib(a,b,c,d){O.ha.write(a,
b,0,d,c,!1);return 0}}},Lc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Mc=null,Nc={},Oc=[],Pc=1,R=null,Ka=!1,Oa=!0,Qc={},N=class{name="ErrnoError";constructor(a){this.la=a}},Rc=class{La={};node=null;get flags(){return this.La.flags}set flags(a){this.La.flags=a}get position(){return this.La.position}set position(a){this.La.position=a}},Sc=class{ia={};ha={};Da=null;constructor(a,b,c,d){a||=this;this.parent=a;this.va=a.va;this.id=Pc++;this.name=b;this.mode=c;this.Fa=d;this.za=this.pa=this.oa=Date.now()}get read(){return 365===
(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function S(a,b={}){if(!a)throw new N(44);b.Ta??(b.Ta=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=Mc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=rc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=qc(e+"/"+a[f]);try{d=Q(d,a[f])}catch(n){if(44===n?.la&&g&&b.vb)return{path:e};throw n;}!d.Da||g&&!b.Ta||(d=d.Da.root);if(40960===(d.mode&61440)&&(!g||b.Ga)){if(!d.ia.Ka)throw new N(52);
d=d.ia.Ka(d);"/"===d.charAt(0)||(d=rc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new N(32);}function Tc(a){for(var b;;){if(a===a.parent)return a=a.va.hb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Uc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function Kc(a){var b=Uc(a.parent.id,a.name);if(R[b]===a)R[b]=a.Ea;else for(b=R[b];b;){if(b.Ea===a){b.Ea=a.Ea;break}b=b.Ea}}
function Q(a,b){var c=P(a.mode)?(c=Vc(a,"x"))?c:a.ia.Ia?0:2:54;if(c)throw new N(c);for(c=R[Uc(a.id,b)];c;c=c.Ea){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ia.Ia(a,b)}function Jc(a,b,c,d){a=new Sc(a,b,c,d);b=Uc(a.parent.id,a.name);a.Ea=R[b];return R[b]=a}function P(a){return 16384===(a&61440)}function Wc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Vc(a,b){if(Oa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Xc(a,b){if(!P(a.mode))return 54;try{return Q(a,b),20}catch(c){}return Vc(a,"wx")}function Yc(a,b,c){try{var d=Q(a,b)}catch(e){return e.la}if(a=Vc(a,"wx"))return a;if(c){if(!P(d.mode))return 54;if(d===d.parent||"/"===Tc(d))return 10}else if(P(d.mode))return 31;return 0}function Zc(a){if(!a)throw new N(63);return a}
function T(a){a=Oc[a];if(!a)throw new N(8);return a}function $c(a,b=-1){a=Object.assign(new Rc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Oc[b])break a;throw new N(33);}a.ta=b;return Oc[b]=a}function ad(a,b=-1){a=$c(a,b);a.ha?.nb?.(a);return a}function bd(a,b){var c=null?.ha.ya,d=c?null:a;c??=a.ia.ya;Zc(c);c(d,b)}var Ic={open(a){a.ha=Nc[a.node.Fa].ha;a.ha.open?.(a)},ua(){throw new N(70);}};function Ec(a,b){Nc[a]={ha:b}}
function Na(a,b){var c="/"===b;if(c&&Mc)throw new N(10);if(!c&&b){var d=S(b,{Ta:!1});b=d.path;d=d.node;if(d.Da)throw new N(10);if(!P(d.mode))throw new N(54);}b={type:a,Lb:{},hb:b,ub:[]};a=a.va(b);a.va=b;b.root=a;c?Mc=a:d&&(d.Da=b,d.va&&d.va.ub.push(b));return a}function cd(a,b,c){var d=S(a,{parent:!0}).node;a=sc(a);if(!a)throw new N(28);if("."===a||".."===a)throw new N(20);var e=Xc(d,a);if(e)throw new N(e);if(!d.ia.Ma)throw new N(63);return d.ia.Ma(d,a,b,c)}function U(a){return cd(a,16895,0)}
function dd(a,b,c){"undefined"==typeof c&&(c=b,b=438);cd(a,b|8192,c)}function La(a,b){if(!vc(a))throw new N(44);var c=S(b,{parent:!0}).node;if(!c)throw new N(44);b=sc(b);var d=Xc(c,b);if(d)throw new N(d);if(!c.ia.Oa)throw new N(63);c.ia.Oa(c,b,a)}function ed(a){var b=S(a,{parent:!0}).node;a=sc(a);var c=Q(b,a),d=Yc(b,a,!0);if(d)throw new N(d);if(!b.ia.Na)throw new N(63);if(c.Da)throw new N(10);b.ia.Na(b,a);Kc(c)}function fd(a,b){a=S(a,{Ga:!b}).node;return Zc(a.ia.qa)(a)}
function Ma(a,b,c=438){if(""===a)throw new N(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=S(a,{Ga:!(b&131072),vb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new N(20);}else{if(e)throw new N(31);d=cd(a,c|511,0);f=!0}if(!d)throw new N(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!P(d.mode))throw new N(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:P(d.mode)&&("r"!==Wc(b)||b&576)?31:Vc(d,Wc(b)):44))throw new N(e);if(b&512&&!f){e=d;e="string"==typeof e?S(e,{Ga:!0}).node:e;if(P(e.mode))throw new N(31);if(32768!==(e.mode&61440))throw new N(28);var g=Vc(e,"w");if(g)throw new N(g);bd(e,{size:0,timestamp:Date.now()})}b&=-131713;e=$c({node:d,path:Tc(d),flags:b,seekable:!0,position:0,ha:d.ha,zb:[],error:!1});e.ha.open&&e.ha.open(e);f&&(c&=511,d="string"==typeof d?S(d,{Ga:!0}).node:d,bd(d,{mode:c&4095|d.mode&-4096,
oa:Date.now(),Jb:void 0}));!h.logReadFiles||b&1||a in Qc||(Qc[a]=1);return e}function gd(a,b,c){if(null===a.ta)throw new N(8);if(!a.seekable||!a.ha.ua)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.ha.ua(a,b,c);a.zb=[]}
function A(a,b,c){a=qc("/dev/"+a);var d=Lc(!!b,!!c);A.fb??(A.fb=64);var e=A.fb++<<8|0;Ec(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,n,t){for(var q=0,z=0;z<t;z++){try{var D=b()}catch(ca){throw new N(29);}if(void 0===D&&0===q)throw new N(6);if(null===D||void 0===D)break;q++;g[n+z]=D}q&&(f.node.za=Date.now());return q},write(f,g,n,t){for(var q=0;q<t;q++)try{c(g[n+q])}catch(z){throw new N(29);}t&&(f.node.pa=f.node.oa=Date.now());return q}});dd(a,d,e)}
var W={},X=a=>{if(!a)return"";var b=xc((m(),u),a);return wc.decode((m(),u).slice(a,b))};function hd(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":T(a).path;if(0==b.length){if(!c)throw new N(44);return a}return a+"/"+b}
function jd(a,b){(m(),w)[a/4]=b.ab;(m(),w)[(a+4)/4]=b.mode;(m(),y)[(a+8)/8]=BigInt(b.jb);(m(),w)[(a+16)/4]=b.uid;(m(),w)[(a+20)/4]=b.cb;(m(),w)[(a+24)/4]=b.Fa;(m(),x)[(a+32)/8]=BigInt(b.size);(m(),v)[(a+40)/4]=4096;(m(),v)[(a+44)/4]=b.Za;var c=b.za.getTime(),d=b.pa.getTime(),e=b.oa.getTime();(m(),x)[(a+48)/8]=BigInt(Math.floor(c/1E3));(m(),y)[(a+56)/8]=BigInt(c%1E3*1E6);(m(),x)[(a+64)/8]=BigInt(Math.floor(d/1E3));(m(),y)[(a+72)/8]=BigInt(d%1E3*1E6);(m(),x)[(a+80)/8]=BigInt(Math.floor(e/1E3));(m(),
y)[(a+88)/8]=BigInt(e%1E3*1E6);(m(),x)[(a+96)/8]=BigInt(b.eb);return 0}var Y=void 0;function Za(a,b,c,d){if(k)return I(3,1,a,b,c,d);b=M(b);try{b=X(b);b=hd(a,b);if(c&-8)return-28;var e=S(b,{Ga:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Vc(e,a)?-2:0}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.la}}var kd=()=>{var a=Number((m(),y)[Y/8]);Y+=8;return a},ld=()=>{var a=(m(),v)[+Y/4];Y+=4;return a};
function $a(a,b,c){if(k)return I(4,1,a,b,c);Y=c=M(c);try{var d=T(a);switch(b){case 0:var e=ld();if(0>e)break;for(;Oc[e];)e++;return ad(d,e).ta;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ld(),d.flags|=e,0;case 5:return e=kd(),(m(),Ga)[(e+0)/2]=2,0;case 6:case 7:return 0}return-28}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.la}}
function ab(a,b){if(k)return I(5,1,a,b);b=M(b);try{var c=T(a),d=c.node,e=c.ha.qa;a=e?c:d;e??=d.ia.qa;Zc(e);var f=e(a);return jd(b,f)}catch(g){if("undefined"==typeof W||"ErrnoError"!==g.name)throw g;return-g.la}}var Z=(a,b,c)=>Bc(a,(m(),u),b,c);function bb(a,b){if(k)return I(6,1,a,b);a=M(a);b=M(b);try{if(0===b)return-28;var c=Ac("/")+1;if(b<c)return-68;Z("/",a,b);return c}catch(d){if("undefined"==typeof W||"ErrnoError"!==d.name)throw d;return-d.la}}
function cb(a,b,c){if(k)return I(7,1,a,b,c);Y=c=M(c);try{var d=T(a);switch(b){case 21509:return d.ka?0:-59;case 21505:if(!d.ka)return-59;if(d.ka.Ba.rb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=kd();(m(),v)[e/4]=25856;(m(),v)[(e+4)/4]=5;(m(),v)[(e+8)/4]=191;(m(),v)[(e+12)/4]=35387;for(var f=0;32>f;f++)(m(),r)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.ka?0:-59;case 21506:case 21507:case 21508:if(!d.ka)return-59;if(d.ka.Ba.sb)for(e=
kd(),m(),m(),m(),m(),a=[],f=0;32>f;f++)a.push((m(),r)[e+f+17]);return 0;case 21519:if(!d.ka)return-59;e=kd();return(m(),v)[e/4]=0;case 21520:return d.ka?-28:-59;case 21537:case 21531:kd();if(!d.ha.qb)throw new N(59);return 28;case 21523:if(!d.ka)return-59;d.ka.Ba.tb&&(f=[24,80],e=kd(),(m(),Ga)[e/2]=f[0],(m(),Ga)[(e+2)/2]=f[1]);return 0;case 21524:return d.ka?0:-59;case 21515:return d.ka?0:-59;default:return-28}}catch(g){if("undefined"==typeof W||"ErrnoError"!==g.name)throw g;return-g.la}}
function db(a,b){if(k)return I(8,1,a,b);a=M(a);b=M(b);try{return a=X(a),jd(b,fd(a,!0))}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return-c.la}}function eb(a,b,c,d){if(k)return I(9,1,a,b,c,d);b=M(b);c=M(c);try{b=X(b);var e=d&256;b=hd(a,b,d&4096);return jd(c,e?fd(b,!0):fd(b))}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.la}}
function fb(a,b,c,d){if(k)return I(10,1,a,b,c,d);b=M(b);Y=d=M(d);try{b=X(b);b=hd(a,b);var e=d?ld():0;return Ma(b,c,e).ta}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.la}}
var B={sa:8192,va(){return Jc(null,"/",16895,0)},ha:{qa(a){a=a.node;var b=a.Ca.timestamp;return{ab:14,eb:a.id,mode:4480,jb:1,uid:0,cb:0,Fa:0,size:0,za:b,pa:b,oa:b,Ya:4096,Za:0}},Mb(a){var b=a.node.Ca;if(1===(a.flags&2097155))return 260;for(var c of b.na)if(0<c.offset-c.ra)return 65;return 0},nb(a){a.node.Ca.Xa++},qb(){return 28},Ha(){return 28},read(a,b,c,d){a=a.node.Ca;var e=0,f;for(f of a.na)e+=f.offset-f.ra;b=b.subarray(c,c+d);if(0>=d)return 0;if(0==e)throw new N(6);c=d=Math.min(e,d);e=0;for(f of a.na){var g=
f.offset-f.ra;if(d<=g){var n=f.buffer.subarray(f.ra,f.offset);d<g?(n=n.subarray(0,d),f.ra+=d):e++;b.set(n);break}else n=f.buffer.subarray(f.ra,f.offset),b.set(n),b=b.subarray(n.byteLength),d-=n.byteLength,e++}e&&e==a.na.length&&(e--,a.na[e].offset=0,a.na[e].ra=0);a.na.splice(0,e);return c},write(a,b,c,d){a=a.node.Ca;b=b.subarray(c,c+d);c=b.byteLength;if(0>=c)return 0;0==a.na.length?(d={buffer:new Uint8Array(B.sa),offset:0,ra:0},a.na.push(d)):d=a.na[a.na.length-1];var e=B.sa-d.offset;if(e>=c)return d.buffer.set(b,
d.offset),d.offset+=c,c;0<e&&(d.buffer.set(b.subarray(0,e),d.offset),d.offset+=e,b=b.subarray(e,b.byteLength));d=b.byteLength/B.sa|0;e=b.byteLength%B.sa;for(var f=0;f<d;f++){var g={buffer:new Uint8Array(B.sa),offset:B.sa,ra:0};a.na.push(g);g.buffer.set(b.subarray(0,B.sa));b=b.subarray(B.sa,b.byteLength)}0<e&&(g={buffer:new Uint8Array(B.sa),offset:b.byteLength,ra:0},a.na.push(g),g.buffer.set(b));return c},close(a){a=a.node.Ca;a.Xa--;0===a.Xa&&(a.na=null)}},Ja(){B.Ja.current||(B.Ja.current=0);return"pipe["+
B.Ja.current++ +"]"}};
function gb(a){if(k)return I(11,1,a);a=M(a);try{if(0==a)throw new N(21);var b={na:[],Xa:2,timestamp:new Date};b.na.push({buffer:new Uint8Array(B.sa),offset:0,ra:0});var c=B.Ja(),d=B.Ja(),e=Jc(B.root,c,4096,0),f=Jc(B.root,d,4096,0);e.Ca=b;f.Ca=b;var g=$c({path:c,node:e,flags:0,seekable:!1,ha:B.ha});e.stream=g;var n=$c({path:d,node:f,flags:1,seekable:!1,ha:B.ha});f.stream=n;var t=g.ta;var q=n.ta;(m(),v)[a/4]=t;(m(),v)[(a+4)/4]=q;return 0}catch(z){if("undefined"==typeof W||"ErrnoError"!==z.name)throw z;
return-z.la}}function hb(a){if(k)return I(12,1,a);a=M(a);try{return a=X(a),ed(a),0}catch(b){if("undefined"==typeof W||"ErrnoError"!==b.name)throw b;return-b.la}}function ib(a,b){if(k)return I(13,1,a,b);a=M(a);b=M(b);try{return a=X(a),jd(b,fd(a))}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return-c.la}}
function jb(a,b,c){if(k)return I(14,1,a,b,c);b=M(b);try{b=X(b);b=hd(a,b);if(c)if(512===c)ed(b);else return-28;else{a=b;var d=S(a,{parent:!0}).node;if(!d)throw new N(44);var e=sc(a),f=Q(d,e),g=Yc(d,e,!1);if(g)throw new N(g);if(!d.ia.Qa)throw new N(63);if(f.Da)throw new N(10);d.ia.Qa(d,e);Kc(f)}return 0}catch(n){if("undefined"==typeof W||"ErrnoError"!==n.name)throw n;return-n.la}}var kb=()=>Pa("");function lb(a){a=M(a);Aa(a,!ba,1,!aa,1048576,!1);Ba()}
var md=a=>{if(!(a instanceof $b||"unwind"==a))throw a;},mc=a=>{if(!qa)try{if(a(),!(J||0<H))try{k?Qb()&&Tb(ra):Eb(ra)}catch(b){md(b)}}catch(b){md(b)}};function Ca(a){a=M(a);"function"===typeof Atomics.Ab&&(Atomics.Ab((m(),v),a/4,a).value.then(Ea),a+=228,Atomics.store((m(),v),a/4,1))}var Ea=()=>mc(()=>{var a=Qb();a&&(Ca(a),Vb())});function mb(a,b){a=M(a);b=M(b);a==b?setTimeout(Ea):k?postMessage({Pa:a,Aa:"checkMailbox"}):(a=G[a])&&a.postMessage({Aa:"checkMailbox"})}var nd=[];
function nb(a,b,c,d,e){e=M(e);d/=2;nd.length=d;b=e/8;for(c=0;c<d;c++)(m(),x)[b+2*c]?nd[c]=(m(),x)[b+2*c+1]:nd[c]=(m(),Ha)[b+2*c+1];a=(0,od[a])(...nd);"bigint"==typeof a&&(a=M(a));return a}var ob=()=>{J=!1;H=0};function pb(a){return(a=M(a))?-52:0}function qb(a){a=M(a);k?postMessage({Aa:"cleanupThread",yb:a}):lc(G[a])}function rb(){}var pd={},zb=()=>performance.timeOrigin+performance.now();
function sb(a,b){if(k)return I(15,1,a,b);pd[a]&&(clearTimeout(pd[a].id),delete pd[a]);if(!b)return 0;var c=setTimeout(()=>{delete pd[a];mc(()=>Ub(a,performance.timeOrigin+performance.now()))},b);pd[a]={id:c,Ob:b};return 0}
function tb(a,b,c,d){a=M(a);b=M(b);c=M(c);d=M(d);var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(m(),y)[a/8]=BigInt(60*g);(m(),v)[b/4]=Number(f!=e);b=n=>{var t=Math.abs(n);return`UTC${0<=n?"-":"+"}${String(Math.floor(t/60)).padStart(2,"0")}${String(t%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Z(a,c,17),Z(b,d,17)):(Z(a,d,17),Z(b,c,17))}var wb=()=>Date.now(),qd=1;
function ub(a,b,c){c=M(c);if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(qd)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(m(),x)[c/8]=BigInt(a);return 0}var vb=()=>{},xb=()=>{H+=1;throw"unwind";},yb=()=>BigInt(2147483648),Ab=()=>navigator.hardwareConcurrency;
function Bb(a){a=M(a);var b=(m(),u).length;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-p.buffer.byteLength+65535)/65536|0;try{p.grow(BigInt(d));sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}
var rd={},td=()=>{if(!sd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in rd)void 0===rd[b]?delete a[b]:a[b]=rd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);sd=c}return sd},sd;function Cb(a,b){if(k)return I(16,1,a,b);a=M(a);b=M(b);var c=0,d=0,e;for(e of td()){var f=b+c;(m(),y)[(a+d)/8]=BigInt(f);c+=Z(e,f,Infinity)+1;d+=8}return 0}
function Db(a,b){if(k)return I(17,1,a,b);a=M(a);b=M(b);var c=td();(m(),y)[a/8]=BigInt(c.length);a=0;for(var d of c)a+=Ac(d)+1;(m(),y)[b/8]=BigInt(a);return 0}function Fb(a){if(k)return I(18,1,a);try{var b=T(a);if(null===b.ta)throw new N(8);b.Ua&&(b.Ua=null);try{b.ha.close&&b.ha.close(b)}catch(c){throw c;}finally{Oc[b.ta]=null}b.ta=null;return 0}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return c.la}}
function Gb(a,b){if(k)return I(19,1,a,b);b=M(b);try{var c=T(a),d=c.ka?2:P(c.mode)?3:40960===(c.mode&61440)?7:4;(m(),r)[b]=d;(m(),Ga)[(b+2)/2]=0;(m(),x)[(b+8)/8]=BigInt(0);(m(),x)[(b+16)/8]=BigInt(0);return 0}catch(e){if("undefined"==typeof W||"ErrnoError"!==e.name)throw e;return e.la}}
function Hb(a,b,c,d){if(k)return I(20,1,a,b,c,d);b=M(b);c=M(c);d=M(d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var n=Number((m(),y)[a/8]),t=Number((m(),y)[(a+8)/8]);a+=16;var q=e,z=(m(),r),D=n,ca=t,K=f;if(0>ca||0>K)throw new N(28);if(null===q.ta)throw new N(8);if(1===(q.flags&2097155))throw new N(8);if(P(q.node.mode))throw new N(31);if(!q.ha.read)throw new N(28);var na="undefined"!=typeof K;if(!na)K=q.position;else if(!q.seekable)throw new N(70);var oa=q.ha.read(q,z,D,ca,K);na||(q.position+=
oa);var L=oa;if(0>L){var pa=-1;break a}b+=L;if(L<t)break;"undefined"!=typeof f&&(f+=L)}pa=b}(m(),y)[d/8]=BigInt(pa);return 0}catch(V){if("undefined"==typeof W||"ErrnoError"!==V.name)throw V;return V.la}}function Ib(a,b,c,d){if(k)return I(21,1,a,b,c,d);b=M(b);d=M(d);try{if(isNaN(b))return 61;var e=T(a);gd(e,b,c);(m(),x)[d/8]=BigInt(e.position);e.Ua&&0===b&&0===c&&(e.Ua=null);return 0}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return f.la}}
function Jb(a,b,c,d){if(k)return I(22,1,a,b,c,d);b=M(b);c=M(c);d=M(d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var n=Number((m(),y)[a/8]),t=Number((m(),y)[(a+8)/8]);a+=16;var q=e,z=(m(),r),D=n,ca=t,K=f;if(0>ca||0>K)throw new N(28);if(null===q.ta)throw new N(8);if(0===(q.flags&2097155))throw new N(8);if(P(q.node.mode))throw new N(31);if(!q.ha.write)throw new N(28);q.seekable&&q.flags&1024&&gd(q,0,2);var na="undefined"!=typeof K;if(!na)K=q.position;else if(!q.seekable)throw new N(70);var oa=q.ha.write(q,
z,D,ca,K,void 0);na||(q.position+=oa);var L=oa;if(0>L){var pa=-1;break a}b+=L;if(L<t)break;"undefined"!=typeof f&&(f+=L)}pa=b}(m(),y)[d/8]=BigInt(pa);return 0}catch(V){if("undefined"==typeof W||"ErrnoError"!==V.name)throw V;return V.la}}function Lb(a,b){a=M(a);b=M(b);try{return uc((m(),u).subarray(a,a+b)),0}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return c.la}}k||jc();R=Array(4096);Na(O,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");Ec(259,{read:()=>0,write:(d,e,f,g)=>g,ua:()=>0});dd("/dev/null",259);Dc(1280,Gc);Dc(1536,Hc);dd("/dev/tty",1280);dd("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(uc(a),b=a.byteLength);return a[--b]};A("random",c);A("urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");Na({va(){var b=Jc(a,"fd",16895,73);b.ha={ua:O.ha.ua};b.ia={Ia(c,d){c=+d;var e=T(c);c={parent:null,va:{hb:"fake"},ia:{Ka:()=>e.path},id:c+1};return c.parent=c},Wa(){return Array.from(Oc.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();k||(h.wasmMemory?p=h.wasmMemory:p=new WebAssembly.Memory({initial:BigInt((h.INITIAL_MEMORY||16777216)/65536),maximum:BigInt(32768),shared:!0,address:"i64"}),sa());
h.noExitRuntime&&(J=h.noExitRuntime);h.print&&(ka=h.print);h.printErr&&(l=h.printErr);h.wasmBinary&&(la=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();var od=[Kb,ic,oc,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,sb,Cb,Db,Fb,Gb,Hb,Ib,Jb],Pb,Qb,Aa,Fa,Rb,Sb,Tb,Ub,Vb,Qa,Wb,Xb,Yb,Zb,Wa;
function Mb(){var a=C;a=Object.assign({},a);var b=d=>()=>Number(d()),c=d=>e=>d(BigInt(e));a.T=(d=>(e,f,g)=>d(e,BigInt(f?f:0),BigInt(g?g:0)))(a.T);a.V=b(a.V);a.X=(d=>(e,f,g,n,t,q)=>d(BigInt(e),f,g,n,t,q))(a.X);a.Z=(d=>(e,f,g,n,t)=>d(e,BigInt(f),g,BigInt(n),t))(a.Z);a._=c(a._);a.$=c(a.$);a.da=(d=>(e,f)=>d(BigInt(e),BigInt(f)))(a.da);a.ea=c(a.ea);a.fa=(d=>e=>Number(d(BigInt(e))))(a.fa);a.ga=b(a.ga);return a}
function ud(a=[]){var b=Pb;a.unshift(ea);var c=a.length,d=Yb(8*(c+1)),e=d;a.forEach(g=>{var n=(m(),y),t=e/8,q=BigInt,z=Ac(g)+1,D=Yb(z);Z(g,D,z);n[t]=q(D);e+=8});(m(),y)[e/8]=BigInt(0);try{var f=b(c,BigInt(d));Eb(f,!0)}catch(g){md(g)}}
function ya(a=da){function b(){h.calledRun=!0;if(!qa&&(Ja(),ta?.(h),h.onRuntimeInitialized?.(),h.noInitialRun||ud(a),!k)){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();nc.push(c)}bc(nc)}}if(0<E)dc=ya;else if(k)ta?.(h),Ja();else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)cc.push(h.preRun.shift());bc(cc);0<E?dc=ya:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),
1);b()},1)):b()}}var C;k||(C=await (xa()),ya());Ia?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ta=a;ua=b});
;return moduleRtn}export default Module;var isPthread=globalThis.self?.name?.startsWith("em-pthread");isPthread&&Module();
